### ISSUE TITLE
Wrong Pot strings

### ISSUE THREAD

**Issue by sauvainr** [woothemes/woocommerce-language-packs#10]
Hi,
I had to install a zh_TW woocommerce for a customer and I noticed couple of string cannot be translated.
The .pot strings are either missing or have a different lower/upper case than the code:

My Account
New Password
Current Password
Password Change (leave blank to leave unchanged)
Thank you for your purchase

**Comment by mikejolley** [comment]
Translation should be done on https://translate.wordpress.org/projects/wp-plugins/woocommerce going forward - this repo is deprecated.

**Comment by sauvainr** [comment]
Ok thanks, 
As I dont see any option to modify the .pot file do you know where to address this issue?
This issue is affecting every languages for those string. I would be good to solve it.

**Comment by claudiosmweb** [comment]
.pot are deprecated now.
