### ISSUE TITLE
Download impossible from Woocommerce plugin Zh-CN

### ISSUE THREAD

**Issue by Couiljer** [woothemes/woocommerce-language-packs#12]
Hi there, 

I've an issue with language package downloads when I try to set up Chinese on my wordpress. Here is the error message I get : 
"Woocommerce translation 中文 (中国)(zh_CN) can not be found in : https://github.com/woothemes/woocommerce-language-packs/raw/v2.5.2/packages" 

Does anybody know how to fix it ? 

thanks, 

Jérémy.

**Comment by claudiosmweb** [comment]
We don't use this repo for 2.5. See https://woocommerce.wordpress.com/2015/09/17/moving-languages-packs-to-wordpress-org/
