### ISSUE TITLE
Woocommerce not found rus lang :(

### ISSUE THREAD

**Issue by curaquartz** [woothemes/woocommerce-language-packs#13]
Woocommerce translation Русский(ru_RU) can not be found in : https://github.com/woothemes/woocommerce-language-packs/raw/v2.5.5/packages

**Comment by curaquartz** [comment]
Error 404 — Page NOT Found

**Comment by claudiosmweb** [comment]
Because we don't use this anymore since 2.5.0.

**Comment by claudiosmweb** [comment]
https://woocommerce.wordpress.com/2015/09/17/moving-languages-packs-to-wordpress-org/
