### ISSUE TITLE
No tag for 2.4.8 woocommerce version

### ISSUE THREAD

**Issue by andriibuts** [woothemes/woocommerce-language-packs#9]
There are no tag for 2.4.8 woocommerce version in this repositiory, so thre translations can't be installed.

When I try to install new version I get this error `Woocommerce translation Русский(ru_RU) can not be found in : https://github.com/woothemes/woocommerce-language-packs/raw/v2.4.8/packages`

Wordpress version: 4.3.1
WooCommerce version: 2.4.8

**Comment by claudiosmweb** [comment]
Done
